language: go
os: linux
dist: bionic
env:
  - IMAGE_REPO=localhost:5000
go:
  - "1.13.3"
go_import_path: github.com/GoogleContainerTools/kaniko
jobs:
  include:
    - script:
      - make test
    - script:
      - ./travis-integration-suite-setup.sh
      - ./integration-test.sh -run TestRun
    - stage: build-images
      script:
        - make images
