language: go
os: linux
dist: bionic
env:
  - IMAGE_REPO=localhost:5000
go:
  - "1.13.3"
go_import_path: github.com/GoogleContainerTools/kaniko
jobs:
  include:
    - name: unit-test
      script:
        - make test
    - name: integration-test-run
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
        - docker run -d -p 5000:5000 --restart always --name registry registry:2
      script:
        - make integration-test-run
    - name: integration-test-misc
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
        - docker run -d -p 5000:5000 --restart always --name registry registry:2
      script:
        - make integration-test-misc
    - stage: build-images
      script:
        - make images
