language: go
os: linux
dist: bionic
env:
  - IMAGE_REPO=localhost:5000
go:
  - "1.13.3"
go_import_path: github.com/GoogleContainerTools/kaniko
jobs:
  include:
    - name: unit-test
      script:
        - make test
    - name: integration-test
      before_install:
        - ./travis-integration-suite-setup.sh
      script:
        - ./integration-test.sh -run TestRun
        - make images
