language: go
os: linux

go:
  - "1.10"
go_import_path: github.com/GoogleContainerTools/kaniko

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -q libseccomp-dev


script:
  - make test
