required = [
  "k8s.io/client-go/discovery",
]

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "a40133b69fbd73ee655606a9bf5f8b9b9bf758dd"

[[override]]
  name = "github.com/opencontainers/runc"
  revision = "1f11dc5dba5213400482cd974db20ee1408d2c7f"

[[override]]
  name = "github.com/ishidawataru/sctp"
  revision = "07191f837fedd2f13d1ec7b5f885f0f3ec54b1cb"

[[override]]
  name = "github.com/containers/storage"
  revision = "1e5ce40cdb84ab66e26186435b1273e04b879fef"
  source = "github.com/containers/storage"

[[override]]
  name = "github.com/vishvananda/netlink"
  revision = "b2de5d10e38ecce8607e6b438b6d174f389a004e"

[[override]]
  name = "google.golang.org/grpc"
  revision = "8124abf74e7633d82a5b96585b0da487d0e6eed0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.56"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "31e00cede111067bae48bfc2cbfc522b0b36207f"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.6.0"

[[constraint]]
  name = "github.com/minio/HighwayHash"
  version = "1.0.0"

[[override]]
  name = "github.com/genuinetools/amicontained"
  version = "0.4.0"

[[override]]
  name = "github.com/containers/image"
  revision = "495da41bd26c50be62fa07ae903ea2ee54c00283"
