apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
spec:
  containers:
  - name: kaniko-warmer
    image: gcr.io/sharif-test/warmer@sha256:9bf8affcf6630a9b17298e54b79247a22516aebff0c88733f04e6e2974ca58c4
    args: ["-c /cache",
           "-i gcr.io/google-appengine/debian9",
           "-vdebug"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
      - name: kaniko-cache
        mountPath: /cache
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: default-token-wtlnt
    - name: kaniko-cache
      persistentVolumeClaim:
              claimName: kaniko-cache-claim

