timeout: 1800s

steps:

# Sign all of the images we just released
- name: $_COSIGN_IMAGE
  args: ['sign', '-kms', 'gcpkms://projects/$PROJECT_ID/locations/global/keyRings/cosign/cryptoKeys/cosign', 
  # executor image
  'gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME',
  "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:latest",

  # slim executor images
  "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME-slim",
  "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:slim",

  # debug image
  "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME-debug",
  "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:debug",

  # warmer image
  "gcr.io/$PROJECT_ID/{_WARMER_IMAGE_NAME}:$TAG_NAME",
  "gcr.io/$PROJECT_ID/{_WARMER_IMAGE_NAME}:latest",
  ]

substitutions:
  _EXECUTOR_IMAGE_NAME: executor
  _WARMER_IMAGE_NAME: warmer
  _COSIGN_IMAGE: gcr.io/projectsigstore/cosign/ci/cosign:2f4694c6c92f634189bfb78db9ddebba358e1822@sha256:6bfaf6e1e14d316bd971df700a7df7ad2a3dbcfa3c2fe5a00afdc3b595c11103
